project_id = "ia-contra-golpes"
region     = "southamerica-east1"
zone       = "southamerica-east1-a"
email      = "robertovictor.rj1@gmail.com"
env        = "env"
solution   = "ia-contra-golpes"
service_account = "451790203589-compute@developer.gserviceaccount.com"