---
name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/
        run: |
          terraform state rm google_cloud_run_v2_service.handler-dev
          terraform destroy -auto-approve
