name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TF_DIR: ${{ github.workspace }}/terraform

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Linter Setup
        run: |
          pip install black
          chmod +x ./ci/lint.sh
      - name: Run
        run: ./ci/lint.sh

  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '6.38.0'
      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Terraform Init and Apply
        run: |
          cd $TF_DIR
          terraform init
          terraform plan
          terraform apply -auto-approve
